# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bt0l0uiG4tuEdUkcvnBsPBdlq7AOoJXziyfRtCskGAhVDDfeDUVEX3FaSuOaS7KpBaqCSz3d/Z4kwHVUD9oE6OJALX1vt8jO5Kz4M3bZWADXHY4RPnbf74pZLBHAaUgR0c6knS2GIk8yCakrKyoddsTDq/b88scpwO2dJyyjm1h620VCM8VfyZ/KOIUFDy9Bi24zcalwcDnsF0zKbtX626AfBWQ/2xvC5HuG7cuqI0FfATDpqzfE7W5LEswyw/XAH/PWMpb7qOVb6wOYqLDwyvOHEKb1EDTxTj/4VrAZdHADyUnwkM9ulemjnVkLPCEUZdkphwdXyRYt+b5AbBcFD1nrN+rC6oGOcFOIZdJJtTnXlvf7Vgf9SA1sEgY73XK3IsH3Oyb2bCt4XGrnBhfE6HcAh02t0p4qK4iKRwiYc/2YYSwOhuBE5RHQOl1bbdfh+rGrDSvXWM/y5pdPURc2fj5Ceu9eE0Ljp3AJT5zzX6kJBn7mGKvV3SJqUoHEvjBPjU0fZsS5kDIf0evCoHmmAz5NkGvjJ/auDb9P7L7sqnSUYzGdPdjdOsSmceLyfMZ7plWyboQG4DEjLrVzrMOMzvBH3+ItGsYYYJ26uxtqJaA6wPlkqe+eq40TXGKNaBR8QOOHV9B8w4clgwFlaqi5nzKS4+QVbMZmWqcO+xnWPGk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
