travis:
  secure:
    BINSTAR_TOKEN: RJSrI/TCqUhFe6zDROXfZPQZucdS8bCXTKTrz2mM6xGfei35KtSwYStrs6Mecas0ug6Wi9zN7BurJ8VHEQLWm9skoLgD2UO2nes2CaLKYXS8NSVP+UiYGBOQsMLPM9/iD6uUlwBC/ni/bkR/PsJ4342lOd72wUNXBTPf7ePaOLEVUzyBVcQLt/mvuqs0K11psv68fqDjP++08XmkTKxbcEcowBTRw/J+wjPvRgIjVTK84v6QTHIHgA4hHX+ccETvYulN9QwbxNaigbeZIFCL3nEc1HMqryovQVhWbgur6riQyjco+gK2qoZSmGmkHzHWzK97FQcax0kREilrvf9cmGpryRCw39rqGIN7VH3064ZCgNhw0aD2qKsv3hKtjCfysTCU6+MEtFcuBWHnz0Ss0ZnAp1UwmKvn7IPPaaONUpxe1Ye+kiKFaMsRk0MYUuan5yzLJinxElmu5pl3lIHWo1YclTXDIJKqxZfnq7I5zXYtN82rsX7Auw7Vm88s+InRQgRYVNd1f+hX80P+FZ/dy6Yxll58pRrBUUyp7oy9Gw+TYWsqrF+9+MYFffFXfjjDg3Lsp8De2+KpY+ZV/V7Genn2P8VN4Y06TGbUBChgmhFhROJEdwlWYEhERNEbUX/L/GopFKw7077civquAT2aEej2jJt39y8Qx2Ig1TOxNeo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
