travis:
  secure:
    BINSTAR_TOKEN: pw5kHwJT+VHLATN5gI21/2H50EwS+KNfiiRQhz6HpGmo0feZVKnNczpy0ahvTlEmOylOmEE/2g1Zsn4hylv22uSyfqyLMqrAqHg8MlPaR62HF7bO4rj3G2+eoF7CRg0ki1arCBre/QXMp3O8E85JiAac08YCBkW2VqwGoC9JRbfjdcNkz0sSPK0w23SY6B4L8AXrjqPIIVlHko1n6w2Be5NDSSn7kQzZWfji+2WdihNh9v4iTQtIZgOigWTrYmxBc6E0oYjkWK3gHyB8pkXqst2btSJortY5pn//C8lrkQkRYczIrxsmBsWRJUFulRxr7m9p9GIFeB7MMuWlbIF5ElsFZTYhG8vS2r1OyoG7cY447VkYyAp70h6bYoOtk3sjXWBEise7c4hAsur4qdtjLOBQ4rhBFS0LpabUQgXz/ZiTE/beWUDkDDcOsHE12xb6p0OAjSLHDIbs5BR0xTUrcH2ero/ahfIYxuLbzpKvraRlTbKHilw+4FIMVnVaQo997Oe/J8tfPhMJsebAIXN+qDXcchJdvmHKPvXV5h6NzfM9epauf5kDfYkfDc7NwvSoOmEId/hQvVgBeFM/5dXSwIbM2Nv7FZ3tljsXkjAn6AXccGJyRVt6gmzCKJYMlobnwcyyrVSqLTbrr/LzjWpoQtVLUEWJdvFJxmiutwsQKXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
