travis:
  secure:
    BINSTAR_TOKEN: bt0l0uiG4tuEdUkcvnBsPBdlq7AOoJXziyfRtCskGAhVDDfeDUVEX3FaSuOaS7KpBaqCSz3d/Z4kwHVUD9oE6OJALX1vt8jO5Kz4M3bZWADXHY4RPnbf74pZLBHAaUgR0c6knS2GIk8yCakrKyoddsTDq/b88scpwO2dJyyjm1h620VCM8VfyZ/KOIUFDy9Bi24zcalwcDnsF0zKbtX626AfBWQ/2xvC5HuG7cuqI0FfATDpqzfE7W5LEswyw/XAH/PWMpb7qOVb6wOYqLDwyvOHEKb1EDTxTj/4VrAZdHADyUnwkM9ulemjnVkLPCEUZdkphwdXyRYt+b5AbBcFD1nrN+rC6oGOcFOIZdJJtTnXlvf7Vgf9SA1sEgY73XK3IsH3Oyb2bCt4XGrnBhfE6HcAh02t0p4qK4iKRwiYc/2YYSwOhuBE5RHQOl1bbdfh+rGrDSvXWM/y5pdPURc2fj5Ceu9eE0Ljp3AJT5zzX6kJBn7mGKvV3SJqUoHEvjBPjU0fZsS5kDIf0evCoHmmAz5NkGvjJ/auDb9P7L7sqnSUYzGdPdjdOsSmceLyfMZ7plWyboQG4DEjLrVzrMOMzvBH3+ItGsYYYJ26uxtqJaA6wPlkqe+eq40TXGKNaBR8QOOHV9B8w4clgwFlaqi5nzKS4+QVbMZmWqcO+xnWPGk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
