travis:
  secure:
    BINSTAR_TOKEN: hvCKh4r05H8LiAtelMOJYTpD5s41OIBIYWEqN2tH0jObcV9afA6beCyXVNd2juNul+P+z7eddNUOjF2nxMMjXtdIn58fcYFiOpdcfaadae1R+e9xteyICvVRNJ/EpEXhXkHqQ/WxIjhUYEz5NO5fqRrH0uWaFQT59aJTiLdz8Od2cc2rHml4+vFoWpws/HFI1KGw7V/POw4xuzg+u/p9EycUmlVWGYwCP1GozT9R8w1HKasvUuM9PEvz4P3jns9q5Pe3gwN72s+8Kr1S7/k0kTgeKc3inm2WaBLwWm90WkZ4iMEqSmX4DN22ZYnSOSpnA3kWp16fnfzjQgNKPmNUgC5eCNnUvc9KB6yHslBfX/89VmcuraoncVtqhPAyMXffeIXE0p4v0ZRvErI108yVk83xUkTL7T16b0d2J/HfGHxf9Y1CZw3gXZ2BaqCdMY1To3Kw1Z1CbxmzeDOFJpmQR/pOtSnqpnB6L6pwcGEGohXsi5B/AG72Skr80DCOEujv6xmcooq7rbSQXNE3tR8vhiB95pOeJl8UCarODjY41W5pI+Nk/tivaVNTDIC23sUE6M9WAs/fxDamXsI5qWMbLW+7+rJE18DiuF8IdBq2h0qVlh7nREcqLtgElquu1C7vuXwx4adO6ciou4yx8LaIFm0vm5SEQ3c4h4FH6pnXH3U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
